### ISSUE TITLE
Change `@w` to `{?}` in UriMapping handlers

### ISSUE THREAD

**Issue by warpech** [Starcounter/PlaygroundKeeper#6]
Since Starcounter 2.2, `{?}` should be used instead of `@w` in `OntologyMap` according to the [release notes](http://starcounter.io/starcounter-2-2-release-notes/).

Old usage found on line: https://github.com/Starcounter/PlaygroundKeeper/blob/5aa56361299b4f3fe6c3819f6e1fe7d62c9ba7ba/src/PlaygroundKeeper/Program.cs#L154

**Comment by miyconst** [comment]
Done. Thanks for noting it.
